name: Java Maven build and Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  IMAGE_NAME: restapi

jobs:
  build_jar:
    name: Build jar file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          settings-path: ".m2/"
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - name: Building jar
        run: mvn $MAVEN_CLI_OPTS clean install --file api/pom.xml
        env:
          MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
      - name: Copying target jar
        run: |
          mkdir myTarget
          cp api/target/*.jar myTarget
      - name: Uploading jar
        uses: actions/upload-artifact@v2
        with:
          name: restapi.jar
          path: myTarget
  build_and_push_to_registry:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase repository name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - name: Download previous generated artifact 
        uses: actions/download-artifact@v1
        with:
          name: restapi.jar
          path: api/target/
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: docker.pkg.github.com/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest
